title: Pavel Skripkin
email: paskripkin@example.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  pskrgag

# Build settings
theme: jekyll-shell-theme
remote_theme: "tareqdandachi/jekyll-shell-theme"
plugins:
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag

header_pages:
  - index.md
  - blog.md
  - about.markdown

permalink: pretty
